import React, { useState } from 'react';
import { X, Printer, Download, CheckCircle, Copy, Shield, FileText } from 'lucide-react';
import { ForensicAuditReport } from '../types';

interface ExportReportModalProps {
  report: ForensicAuditReport;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  report,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = () => {
    const textReport = `=====================================================
PHISHGUARD FORENSIC INCIDENT AUDIT REPORT
=====================================================
INCIDENT ID:      ${report.id}
TIMESTAMP:        ${report.scanTimestamp}
SHA-256 CHECKSUM: ${report.sha256Checksum}
RISK LEVEL:       ${report.riskLevel} (${report.overallScore}/100)
CONFIDENCE:       ${report.confidenceScore}%

EXECUTIVE SUMMARY:
${report.executiveSummary}

DOMAIN & IDENTITY OSINT:
- Extracted Domain: ${report.domainAuth.extractedDomain}
- Domain Age:       ${report.domainAuth.domainAgeDays} days
- Spoofing Detected:${report.domainAuth.isSpoofed ? 'YES (Target: ' + report.domainAuth.spoofedTarget + ')' : 'NO'}
- SPF Alignment:    ${report.domainAuth.spfStatus}
- DKIM Status:      ${report.domainAuth.dkimStatus}

DOCUMENT METADATA:
- Author Tool:      ${report.docMetadata.authorSoftware}
- PKI Signature:    ${report.docMetadata.hasDigitalCert ? 'VALID' : 'UNSIGNED'}
- Tampering Flag:   ${report.docMetadata.tamperingDetected ? 'DETECTED' : 'CLEAN'}

COMPENSATION BENCHMARK:
- Role Analyzed:    ${report.salarySanity.roleTitle}
- Offered:          ${report.salarySanity.offeredSalary}
- Benchmark Median: ${report.salarySanity.marketMedianSalary}
- Deviation:        ${Math.round(report.salarySanity.deviationPercent)}%

THREATS IDENTIFIED (${report.threats.length}):
${report.threats.map((t, i) => `${i + 1}. [${t.status.toUpperCase()}] ${t.title}\n   Evidence: ${t.evidence}\n   Mitigation: ${t.recommendation}`).join('\n\n')}

=====================================================
GENERATED BY PHISHGUARD OSINT FORENSIC SUITE
=====================================================`;

    navigator.clipboard.writeText(textReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm overflow-y-auto">
      <div className="relative w-full max-w-3xl rounded-2xl bg-slate-900 border border-slate-700 shadow-2xl overflow-hidden my-8">
        {/* Header */}
        <div className="flex items-center justify-between p-4 sm:p-5 border-b border-slate-800 bg-slate-950/80">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-cyan-950/60 border border-cyan-800/50 text-cyan-400">
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-white">
                Official Forensic Incident Report
              </h3>
              <p className="text-xs font-mono text-slate-400">
                CASE FILE #{report.id} • SHA-256 VERIFIED
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Printable Certificate Content */}
        <div className="p-6 sm:p-8 space-y-6 max-h-[70vh] overflow-y-auto font-sans bg-slate-950/90 text-slate-200">
          {/* Top Security Banner */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl bg-slate-900 border border-slate-800">
            <div>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-widest block">
                CYBER FRAUD INTELLIGENCE REPORT
              </span>
              <h4 className="text-lg font-black text-white tracking-tight">
                PhishGuard Forensic Certification
              </h4>
              <p className="text-xs font-mono text-slate-400 mt-0.5">
                Timestamp: {new Date(report.scanTimestamp).toUTCString()}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <div
                className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold uppercase border ${
                  report.riskLevel === 'CRITICAL'
                    ? 'bg-rose-950 text-rose-400 border-rose-800'
                    : report.riskLevel === 'SUSPICIOUS'
                    ? 'bg-amber-950 text-amber-400 border-amber-800'
                    : 'bg-emerald-950 text-emerald-400 border-emerald-800'
                }`}
              >
                {report.riskLevel} RISK ({report.overallScore}/100)
              </div>
            </div>
          </div>

          {/* Cryptographic Proof */}
          <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800 text-xs font-mono">
            <span className="text-slate-500 uppercase block text-[10px] mb-1">Cryptographic Fingerprint:</span>
            <span className="text-cyan-400 break-all">{report.sha256Checksum}</span>
          </div>

          {/* Executive Summary */}
          <div>
            <h5 className="text-xs font-mono uppercase text-slate-400 font-bold mb-2">
              1. Executive Assessment
            </h5>
            <p className="text-sm text-slate-300 leading-relaxed p-3.5 rounded-lg bg-slate-900/60 border border-slate-800">
              {report.executiveSummary}
            </p>
          </div>

          {/* Technical Telemetry Grid */}
          <div>
            <h5 className="text-xs font-mono uppercase text-slate-400 font-bold mb-2">
              2. Technical Telemetry Findings
            </h5>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-mono">
              <div className="p-3 rounded-lg bg-slate-900 border border-slate-800">
                <span className="text-slate-500 block text-[10px]">DOMAIN REPUTATION:</span>
                <span className="text-white font-bold">{report.domainAuth.extractedDomain}</span>
                <span className="text-slate-400 block mt-1">Age: {report.domainAuth.domainAgeDays} days | SPF: {report.domainAuth.spfStatus}</span>
              </div>
              <div className="p-3 rounded-lg bg-slate-900 border border-slate-800">
                <span className="text-slate-500 block text-[10px]">DOCUMENT ARTIFACTS:</span>
                <span className="text-white font-bold">{report.docMetadata.authorSoftware}</span>
                <span className="text-slate-400 block mt-1">PKI Seal: {report.docMetadata.hasDigitalCert ? 'Verified' : 'Unsigned'}</span>
              </div>
            </div>
          </div>

          {/* Threat List */}
          <div>
            <h5 className="text-xs font-mono uppercase text-slate-400 font-bold mb-2">
              3. Detected Threat Traces ({report.threats.length})
            </h5>
            <div className="space-y-2 text-xs">
              {report.threats.map((t) => (
                <div key={t.id} className="p-2.5 rounded bg-slate-900/70 border border-slate-800">
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-bold text-white">{t.title}</span>
                    <span className="text-[10px] font-mono text-cyan-400">{t.mitreRef || 'OSINT Rule'}</span>
                  </div>
                  <p className="text-slate-300">{t.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer actions */}
        <div className="p-4 border-t border-slate-800 bg-slate-950 flex flex-wrap items-center justify-between gap-3">
          <button
            onClick={handleCopyText}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-800 text-xs font-mono text-slate-300 hover:bg-slate-700 hover:text-white transition"
          >
            {copied ? (
              <>
                <CheckCircle className="w-4 h-4 text-emerald-400" />
                <span className="text-emerald-400">Report Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy Text Dossier</span>
              </>
            )}
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-mono text-white transition"
            >
              <Printer className="w-4 h-4" />
              <span>Print Dossier</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-xs font-mono font-bold text-slate-950 transition shadow-lg shadow-cyan-500/20"
            >
              <Download className="w-4 h-4" />
              <span>Save Official PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
